### ISSUE TITLE
Bitte mir push access geben oder das BMBF-Banner selber hochladen

### ISSUE THREAD

**Issue by jonasrpunkt** [zapf-berlin/sommer17-webseite#74]
Jo ich hab auf der Unterstützer-Seite durch übelste Haxx0r-skillz den Code für das BMBF-Logo eingefügt, aber ich kann das Logo net hochladen.

**Comment by JanLuca** [comment]
Du fügst das Bild einfach im Ordner static/img/ ein, siehe Beispiel content/zeitplan.md und static/img/Ablaufplan.svg, wie das geht

**Comment by jonasrpunkt** [comment]
Ja genau das habe ich versucht, und dann kam folgende schöne Meldung:
"sommer17-webseite/static/img/sponsor
Uploads are disabled.
File uploads require push access to this repository."

**Comment by jonasrpunkt** [comment]
Jan, falls du das machen kannst/willst: Da gibts das Banner: https://zapf.in/konstanz/2016/images/sponsoren/BMBF.jpg
^.^

**Comment by JanLuca** [comment]
Solved by #77.
